substitutions:
  _AR_HOSTNAME: "us-central1-docker.pkg.dev"
  _DEPLOY_REGION: "us-central1"
  _SERVICE_NAME: "backend-agent"

steps:
  # 1. Build the Container Image using the Dockerfile in backend-agent/
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/backend:$COMMIT_SHA'
      - './backend-agent'
    id: 'Build Backend'

  # 2. Push the Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/backend:$COMMIT_SHA'
    id: 'Push Backend'

  # 3. Deploy the new image to the existing Cloud Run Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '$_SERVICE_NAME'
      - '--platform=managed'
      - '--image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/backend:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: 'Deploy Backend'

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY